com.huffmanproj.Node.class: com.huffmanproj.Node.java
	javac com.huffmanproj.Node.java

com.huffmanproj.MinHeap.class: com.huffmanproj.MinHeap.java
	javac com.huffmanproj.MinHeap.java
  
com.huffmanproj.ReadInput.class: com.huffmanproj.ReadInput.java
	javac com.huffmanproj.ReadInput.java
  
com.huffmanproj.HuffmanCoding: com.huffmanproj.HuffmanCoding.java com.huffmanproj.Node.class com.huffmanproj.MinHeap.class com.huffmanproj.ReadInput.class
	javac com.huffmanproj.HuffmanCoding.java
  
clean:
	rm *.class