Node.class: Node.java
	javac Node.java

MinHeap.class: MinHeap.java
	javac MinHeap.java
  
ReadInput.class: ReadInput.java
	javac ReadInput.java
  
HuffmanCoding: HuffmanCoding.java Node.class MinHeap.class ReadInput.class
	javac HuffmanCoding.java
  
clean:
	rm *.class